- name: update cache repo #apt update
  apt:
    update_cache: yes

- name: Install nginx #apt install nginx -y
  apt:
    name: nginx

- name: create directory
  file:
    path: /website
    state: directory

- name: Copy files website
  copy:
    src: "{{ item }}"
    dest: /var/www/html
  with_fileglob:
    - "files/html/*"